---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            files: ^README\\.md$
    - repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
            args: [--max-line-length=120, --extend-ignore=E203]
    - repo: https://github.com/psf/black
      rev: 24.8.0
      hooks:
          - id: black
    # - repo: https://github.com/adrienverge/yamllint.git
    #   rev: v1.29.0
    #   hooks:
    #       - id: yamllint
    #         args: [--format, parsable, --strict, rules: {line-length: {max: 120}}]

