FROM apache/airflow:3.0.3-python3.10
USER root

RUN apt-get update && apt-get install -y build-essential gcc curl && rm -rf /var/lib/apt/lists/* 

RUN pip3 --version

RUN pip3 install uv 

COPY pyproject.toml .

RUN uv sync

USER airflow 
WORKDIR /opt/airflow
COPY /src/ src/

CMD [".venv/bin/python", 'src/run_pipeline']

