FROM python:3.10.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

COPY pyproject.toml .

RUN uv sync

COPY /src/ src/

CMD [".venv/bin/python", "src/run_pipeline.py"]

